# Generated by Django 3.1.5 on 2021-02-01 03:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='media/blog', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Autor')),
                ('categories', models.ManyToManyField(to='category.Category', verbose_name='Categorías')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
