# Generated by Django 3.1.5 on 2021-02-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('file', models.FileField(max_length=500, upload_to='media/portfolio', verbose_name='Archivo de portada')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizado')),
                ('categories', models.ManyToManyField(to='category.Category', verbose_name='Categorías')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
