# Generated by Django 3.1.7 on 2021-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='media/portfolio', verbose_name='Archivo de portada'),
            preserve_default=False,
        ),
    ]
